#!/usr/bin/env bash

if [ -z "$1" ];
then
  echo "provide a commit message"
  exit 1
fi

echo "generating gRPC code from protobuf defintions"
FILES=*/*.proto

for FILE in ${FILES}
do
 docker run --rm -v $(pwd):$(pwd) -w $(pwd) grpc/go \
    protoc --proto_path=. --go_out=plugins=grpc:. ${FILE}
done

echo "publishing gRPC code"
git reset
git add proto
git commit -m "${1}"
git push
