#!/usr/bin/env bash

if [ -z "$1" ];
then
  echo "please describe this version"
  exit 1
fi

echo "Generating gRPC code from proto defintions"
FILES=*/*.proto

for FILE in ${FILES}
do
 docker run --rm -v $(pwd):$(pwd) -w $(pwd) grpc/go \
    protoc --proto_path=. --go_out=plugins=grpc:. ${FILE}
done

echo "Publishing gRPC code"
git reset
git add proto
git commit -m "${1}"
git push
